# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a824abed5819efba3f1a6b4c7a4b496d"
application_url = "https://baths-victor-provincial-dollar.trycloudflare.com"
embedded = true
name = "MetaFields Import/Export Bulk"
handle = "metafields-bulk-import-export"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "skates-world-india.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://baths-victor-provincial-dollar.trycloudflare.com/auth/callback",
  "https://baths-victor-provincial-dollar.trycloudflare.com/auth/shopify/callback",
  "https://baths-victor-provincial-dollar.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
